services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]

  flyway:
    image: flyway/flyway:9
    container_name: flyway-migrator
    depends_on:
      - db
    volumes:
      - ./flyway.conf:/flyway/conf/flyway.conf
      - ./sql:/flyway/sql
    command: -configFiles=/flyway/conf/flyway.conf -connectRetries=60 migrate

  localstack:
    image: localstack/localstack:3
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/etc/localstack/init/ready.d
