spring:
  application:
    name: spring_batch_demo
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:org/springframework/batch/core/schema-postgresql.sql
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        default_schema: mydb
  batch:
    jdbc:
      initialize-schema: always
      platform: postgresql
logging:
  level:
    org.springframework.batch: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
